Add timing out for test methods
apluslms/python-grader-utils pull request #19
Opened 2021-03-22 09:41 UTC by ihalaij1

**What?**

These changes add a default timeout of 60 seconds for test methods to stop infinite loops etc. and to allow feedback to be shown instead of submissions getting stuck in grading.

The timeout is adjustable with a new setting in `test_config.yaml` called `testmethod_timeout` that accepts an integer value.

Graderutils function `result_or_timeout` was slightly modified to raise a new `TimeoutExit` instead of `TimeoutError` so that it is able to timeout test methods even in cases where some library does `except Exception: pass` (for example: Hypothesis).

The above change also fixes an issue where `result_or_timeout` was not able to timeout a function/method where a file handler is repeatedly opened in an infinite loop without ever closing it.

The variable `testmethod_timeout` is implemented in `graderunittest.py` as a global variable. I was unable to figure out a simple solution without using a global variable. Is this fine?

2021-03-22 09:54 UTC, ihalaij1 commented on graderutils/main.py
> +        graderunittest.testmethod_timeout = int(config["testmethod_timeout"])
Is int() needed here?

2021-03-22 20:01 UTC, Mankro requested changes
I suggested small changes and I had questions to ask. In addition, there is a big concern. If the exercise grader calls `result_or_timeout`, what will happen? The signal module supports only one signal handler at a time, thus I suppose the exercise grader (unit tests) can override the timeout defined in grader-utils. Does this cause new issues?

2021-03-25 10:48 UTC, ihalaij1 commented on graderutils/main.py
> +        graderunittest.testmethod_timeout = int(config["testmethod_timeout"])
You're right about that, I tested it. I removed the Int().

2021-03-25 10:50 UTC, ihalaij1 commented on graderutils/graderunittest.py
> +                    raise TimeoutError("Test timed out after {} seconds. Maybe there exists an infinite loop?".format(testmethod_timeout))
I changed it.

2021-03-25 10:50 UTC, ihalaij1 commented on graderutils/graderunittest.py
> +testmethod_timeout = 60
Yes, it is set only once and not changed after that.

2021-03-25 10:59 UTC, ihalaij1 commented on graderutils/graderunittest.py
> +class TimeoutExit(BaseException):
I tested with Hypothesis tests such as below, and with normal `TimeoutError` `result_or_timeout` not able to timeout the testmethod, whereas `TimeoutExit` always works (I suspect Hypothesis does `except TimeoutError: pass` somewhere):

> 
    # Generate random integers in range(0, 10**6 + 1) and pass them
    # as parameter 'i' to the test method.
    @points(40)
    @given(strategies.integers(0, 10**5))
    @settings(max_examples=2, database=None, max_shrinks=1)
    def test_is__prime_with_large_set(self, i):
        """is_prime returns True for prime numbers and False for non-prime numbers for 1000 random positive integers in range(0, 10**6)."""
        if model_is_prime(i):
            self.assertTrue(
                is_prime(i),
                "{} is a prime number but your function says it is not.".format(i)
            )
        else:
            self.assertFalse(
                is_prime(i),
                "{} is not a prime number but your function says it is.".format(i)
            )

Also, with normal `TimeoutError` `result_or_timeout` was not able to timeout an infinite while loop such as this, but `TimeoutExit` works:

> 
    while True:
        f = open("/exercise/somefile.txt", "r")

2021-03-25 11:04 UTC, ihalaij1 commented
You're right that exercise grader (unit tests) can override the timeout defined in grader-utils. But I don't think this is such a big problem. The grader sets the timeout back to the original defined in grader-utils every time a new test method is ran. So, the timeout can only be overridden temporarily, which might actually be useful in some test scenarios(?). 

I tested this and found no bigger problems.

2021-03-25 18:31 UTC, Mankro approved these changes
Excellent, thanks!

2021-03-25 18:33 UTC, merged